apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: myhood
webhooks:
  - clientConfig:
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURZakNDQWtxZ0F3SUJBZ0lVQ3lNSzFXc3R4
        VFY5K2RPcysrZm5iTmtJUkRvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1NURUxNQWtHQTFVRUJoTUNl
        bWd4Q3pBSkJnTlZCQWNUQW1KcU1Rc3dDUVlEVlFRS0V3SmlhakVMTUFrRwpBMVVFQ3hNQ1EwRXhF
        ekFSQmdOVkJBTVRDa3QxWW1WeWJtVjBaWE13SGhjTk1qUXhNakkxTVRJd05EQXdXaGNOCk1qa3hN
        akkwTVRJd05EQXdXakJKTVFzd0NRWURWUVFHRXdKNmFERUxNQWtHQTFVRUJ4TUNZbW94Q3pBSkJn
        TlYKQkFvVEFtSnFNUXN3Q1FZRFZRUUxFd0pEUVRFVE1CRUdBMVVFQXhNS1MzVmlaWEp1WlhSbGN6
        Q0NBU0l3RFFZSgpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOdGt0NjIrTUN2NlVQ
        ZmtuQUNKOVl2d0t5ZGtjYzJuCmEyOFJwZ2NpYmcwMVZZejZjSitiZ0dEL3c0bEhGVjBpZC9GbkZQ
        MzV2dStoN0g0Ritld2tnWFFJaTRiT3BkdzIKNnQrSXVsa0I3WFJneG43cEtwNnBINFZaZXJ5S0hm
        K0h6Z0I4bmJ0ckZONUdzelRFeGhkQUpsRUVkQmxldTVMNQp6d0o4MzJYREVBMkdVcTJiMnpNKysv
        S3RDOWNLRzYvdFVSSEdhd21WUUFGMlJyc2E0cjRkL1Z4d2lrNjh2VDhmCjErelhjSWRTcTJhZ05O
        UmN1L3BLc1I0ZThrMmVpbG1mdzRNaGNPeFVrVHBUNXE0aXlRK1lCYWhYMkNKR3hKY0YKVXBnYnl2
        UzIrNlVibkp6MWRVc3VrQ1Y1Q1hjanF4QWZEWUZWSEk5S2RPU3dKRy9Idk56ZmwvOENBd0VBQWFO
        QwpNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIw
        T0JCWUVGSkduClNzWFZsQStaTjcxNzdwdlkrS2NOSXhHb01BMEdDU3FHU0liM0RRRUJDd1VBQTRJ
        QkFRQlE3ZitkM2lRekF6MlIKTHVjRHhqVGp1aDBFNEsrM1FYeS9wUlh3VVBpSHFHak5LRGQ1YU4z
        cG52UmRzWmwvYnUrTXYxTWZaNFJta2tqMApxMEtIbFdGL2E2RDJvRjRhVk41YUQvLzN3d3ZkaDYv
        Uy9ETFltOUdud1ozUE9NUDVCRFFqbE9hUWFVRW54eHJXCkcrRTVibFE4VVdlYzhjWWxnTU9NVlVI
        eTVjNHBNSDdoeTczQnd2QUw0VlhHTDM3cFVaV01DVWtBaVhoRjBlYVUKdUVNNFZSaWQrbE5MSVdW
        eEY4Yk54Y3Q0aVRzT0x3aVMvL0ZvTmZqSjVRdXFZQTVHZEluSVFCbTZqaytUdjZlbwp1SEtvcUd3
        M3V1MVRvOGRsOUtCYWNuWWJPcS91K0pZZTcvdXgrd0NKMXNvQ251Q3N1OVBxQWFPMi9mZThZNEpM
        CmlNWWZOMy94Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: myhook
        namespace: kube-system
        path: /pods
    failurePolicy: Fail
    sideEffects: NoneOnDryRun
    name: myhook.heyilu.com
    admissionReviewVersions: ["v1", "v1beta1"]
    # namespace选择规则，如果不配置则全部namespace都会生效
    namespaceSelector:
      # 规定：当 namespace 的标签为 heyilu的值在 ["enabled"] 中，则生效
      # 删除 heyilu label: kubectl label namespace default heyilu-
      # 添加 heyilu label: kubectl label namespace default heyilu=enabled
      matchExpressions:
        - key: heyilu
          operator: In
          values: ["enabled"]
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE"]
        resources:   ["pods"]